name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - SupratimRK
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
      
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Edge
        - Firefox (not supported)
        - Safari (not supported)
        - Other
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Extension Version
      description: Which version of the AI Text Rewriter extension are you using?
      placeholder: ex. 2.1.1
    validations:
      required: true
      
  - type: dropdown
    id: model
    attributes:
      label: AI Model Used
      description: Which Gemini model were you using when the bug occurred?
      options:
        - Gemini 2.5 Flash
        - Gemini 2.5 Flash Lite
        - Gemini 2.0 Flash
        - Gemini 2.0 Flash Lite
        - Not applicable
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true